baseURL: https://jexchan.com/
languageCode: zh-cn
defaultContentLanguage: zh-cn
paginate: 10
title: 大圣不是圣
theme: "PaperMod"
enableRobotsTXT: true

menu:
    main:
        - name: Posts
          url: posts/
          weight: 1
        - name: Tags
          url: tags/
          weight: 2
        - name: Archive
          url: archives/
          weight: 3
        - name: Newsletter
          url: https://newsletter.jexchan.com
          weight: 4
        - name: About
          url: about/
          weight: 5
params:
  env: production
  title: Postcard
  description: "大圣不是圣"
  keywords: [Blog, Writing]
  defaultTheme: light
  disableThemeToggle: true
  showtoc: false
  tocopen: false 

  profileMode:
    enabled: true
    title: "Get busy living, or get busy dying."
    imageUrl: 'https://jexchan.com/logo.png'
    imageWidth: 120
    imageHeight: 120
    imageTitle: jexchan 
        
  assets:
      favicon: "https://jexchan.com/favicon32X32.ico"
      favicon16x16: "https://jexchan.com/favicon16X16.ico"
      favicon32x32: "https://jexchan.com/favicon16X16.ico"

